# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_tier', models.CharField(max_length=40)),
                ('car_price', models.IntegerField(default=0)),
                ('sample_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of the price invoice.')),
                ('sample_promotion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='car_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_monitor.Site'),
        ),
    ]
