# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(max_length=15)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_total_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.CharField(max_length=50)),
                ('search_criteria', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('optional_code', models.CharField(max_length=10)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_monitor.Site')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='site_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_monitor.SiteQuery'),
        ),
        migrations.AlterUniqueTogether(
            name='sitequery',
            unique_together=set([('search_time', 'site_id')]),
        ),
    ]
